# Generated by Django 2.0.10 on 2019-01-25 13:45

import allauth.socialaccount.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtoken',
            name='scopes',
            field=allauth.socialaccount.fields.JSONField(blank=True, null=True, verbose_name='allowed scopes'),
        ),
    ]
